#!/usr/bin/env bash

set -eu -o pipefail

# Notes:
# additional paths before nix-darwin:
#   /System/Cryptexes/App/usr/bin
#   /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
#   /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
#   /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
#   /opt/pmk/env/global/bin
#   /Applications/iTerm.app/Contents/Resources/utilities

declare scripts_dir root_dir script parent
scripts_dir=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
root_dir=$(dirname "$scripts_dir")
script=$(basename "$0")
parent=$(basename "$1"); shift

# shellcheck source=/dev/null
source "$scripts_dir/lib.sh"

function nix-darwin:help () {
  echo "$parent $script - setup nix-darwin"
  echo ""
  echo "$script [options]"
  echo ""
  echo "options:"
  echo "  -h, --help                            show brief help"
}

function nix-darwin:check-nix-install () {
  if ! which nix &> /dev/null; then
    log ERROR "Nix package manager undetected - for nix-darwin, intall determinate-systems nix"
    exit 1
  fi
}

function nix-darwin:backup-fish () {
  if [[ ! -L ~/.config/fish/config.fish ]]; then
    log info "Backing up fish config from non-nix config"
    mv ~/.config/fish ~/.config/fish.backup
  fi
}

function nix-darwin:switch () {
  local root_dir=$1

  cd "$root_dir"
  nix develop --command nix-darwin-switch
}

function nix-darwin:install-homebrew () {
  if ! which brew &> /dev/null; then
    log INFO "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  else
    log INFO "Homebrew detected - install skipped"
  fi
}

function nix-darwin:install-homebrew-apps () {
  log INFO "Installing homebrew apps"
  brew install --cask discord
  brew install --cask iterm2
  brew install --cask keymapp
  brew install --cask notion
  brew install --cask visual-studio-code
}

# Process args
declare -A opts
declare o
declare -a unknown_args=()
o=$(getopt --name "$parent $script" -o h -l help -- "$@")
eval set -- "$o"
while true; do
  case "$1" in
    -h|--help)
      opts[help]=true
      shift
      ;;
    --)
      shift
      if [[ -n "$*" ]]; then
        # shellcheck disable=SC2034
        unknown_args=("$@")
      fi
      break
      ;;
    *)
      log --minimal ERROR "Internal error in script \"$parent $script\""
      exit 1
      ;;
  esac
done

# Arg validation
_lib/opts:show-help nix-darwin:help "${opts[help]:-false}"
_lib/opts:validate-unknown-args "${unknown_args[@]}"

# Setup Home Manager
nix-darwin:check-nix-install
nix-darwin:backup-fish
nix-darwin:switch "$root_dir"
nix-darwin:install-homebrew
nix-darwin:install-homebrew-apps
